FROM eclipse-temurin:17-jdk-alpine

ARG REDIRECT_URL
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG COM_URL
ARG CLS_URL
ARG CLG_URL
ARG JOB_URL
ARG SCH_URL
ARG EVT_URL
ARG ETC_URL
ARG WEEKLY_URL

ENV SPRING_PROFILES_ACTIVE=prod
ENV REDIRECT_URL=$REDIRECT_URL
ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV COM_URL=$COM_URL
ENV CLS_URL=$CLS_URL
ENV CLG_URL=$CLG_URL
ENV JOB_URL=$JOB_URL
ENV SCH_URL=$SCH_URL
ENV EVT_URL=$EVT_URL
ENV ETC_URL=$ETC_URL
ENV WEEKLY_URL=$WEEKLY_URL


COPY ./build/libs/*SNAPSHOT.jar project.jar

ENTRYPOINT ["java", "-Duser.timezone=Asia/Seoul", "-jar", "project.jar"]