spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
