#spring:
#  # JPA 관련 설정
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#  # MySQL 데이터베이스 연결 설정
#  datasource:
#    url: jdbc:tc:mysql:8:///testdb
#    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
#    username: test
#    password: test
#
#  # Redis 설정
#  data:
#    redis:
#      host: localhost
#      port: 6379