discord:
  com-url: ${COM_URL}
  cls-url: ${CLS_URL}
  clg-url: data
  job-url: ${JOB_URL}
  sch-url: ${SCH_URL}
  evt-url: ${EVT_URL}
  etc-url: ${ETC_URL}
  weekly-url: ${WEEKLY_URL}

server:
  redirect-url: ${REDIRECT_URL}