name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      REDIRECT_URL: ${{ secrets.REDIRECT_URL }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      COM_URL: ${{ secrets.COM_URL }}
      CLS_URL: ${{ secrets.CLS_URL }}
      CLG_URL: ${{ secrets.CLG_URL }}
      JOB_URL: ${{ secrets.JOB_URL }}
      SCH_URL: ${{ secrets.SCH_URL }}
      EVT_URL: ${{ secrets.EVT_URL }}
      ETC_URL: ${{ secrets.ETC_URL }}
      WEEKLY_URL: ${{ secrets.WEEKLY_URL }}

    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 테스트 및 빌드하기x
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker Hub에 로그인하기
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker 이미지 생성
        run: |
          docker build --build-arg REDIRECT_URL="${{ secrets.REDIRECT_URL }}" \
          --build-arg DB_URL="${{ secrets.DB_URL }}" \
          --build-arg DB_USERNAME="${{ secrets.DB_USERNAME }}" \
          --build-arg DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          --build-arg REDIS_HOST="${{ secrets.REDIS_HOST }}" \
          --build-arg REDIS_PORT="${{ secrets.REDIS_PORT }}" \
          --build-arg COM_URL="${{ secrets.COM_URL }}" \
          --build-arg CLS_URL="${{ secrets.CLS_URL }}" \
          --build-arg CLG_URL="${{ secrets.CLG_URL }}" \
          --build-arg JOB_URL="${{ secrets.JOB_URL }}" \
          --build-arg SCH_URL="${{ secrets.SCH_URL }}" \
          --build-arg EVT_URL="${{ secrets.EVT_URL }}" \
          --build-arg ETC_URL="${{ secrets.ETC_URL }}" \
          --build-arg WEEKLY_URL="${{ secrets.WEEKLY_URL }}" \
          -t knu-notice-server .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag knu-notice-server ${{ secrets.DOCKERHUB_USERNAME }}/knu-notice-server:latest

      - name: Docker Hub에 Docker 이미지 Push하기
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/knu-notice-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 현재 활성화된 환경 확인 (예: blue 환경이 실행 중이면 container 이름에 "blue" 포함)
            if docker ps --filter "name=knu-notice-server-blue" --format "{{.Names}}" | grep -q "knu-notice-server-blue"; then
                echo "Blue 환경이 현재 활성화되어 있습니다. Green 환경으로 배포합니다."
                docker-compose -f docker-compose.green.yml down || true
                docker-compose -f docker-compose.green.yml pull || true
                docker-compose -f docker-compose.green.yml up -d
                sleep 30
                if curl -s http://127.0.0.1:8082/actuator/health | grep -q '"status":"UP"'; then
                    echo "Green 환경 헬스 체크 성공. Nginx를 Green 환경으로 전환합니다."
                    sudo sed -i 's/proxy_pass http:\/\/app_blue;/proxy_pass http:\/\/app_green;/' /etc/nginx/sites-available/default
                    sudo nginx -t && sudo systemctl reload nginx
                    docker-compose -f docker-compose.blue.yml down || true
                else
                    echo "Green 환경 헬스 체크 실패. 배포를 롤백합니다."
                    docker-compose -f docker-compose.green.yml down
                    exit 1
                fi
            else
                echo "Green 환경이 현재 활성화되어 있거나 Blue 환경이 비활성 상태입니다. Blue 환경으로 배포합니다."
                docker-compose -f docker-compose.blue.yml down || true
                docker-compose -f docker-compose.blue.yml pull || true
                docker-compose -f docker-compose.blue.yml up -d
                sleep 30
                if curl -s http://127.0.0.1:8081/actuator/health | grep -q '"status":"UP"'; then
                    echo "Blue 환경 헬스 체크 성공. Nginx를 Blue 환경으로 전환합니다."
                    sudo sed -i 's/proxy_pass http:\/\/app_green;/proxy_pass http:\/\/app_blue;/' /etc/nginx/sites-available/default || true
                    sudo nginx -t && sudo systemctl reload nginx
                    docker-compose -f docker-compose.green.yml down
                else
                    echo "Blue 환경 헬스 체크 실패. 배포를 롤백합니다."
                    docker-compose -f docker-compose.blue.yml down
                    exit 1
                fi
            fi
          
      
       
