name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

#      - name: application.yml 파일 만들기
#        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker Hub에 로그인하기
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker 이미지 생성
        run: docker build -t knu-notice-server .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag knu-notice-server ${{ secrets.DOCKERHUB_USERNAME }}/knu-notice-server:latest

      - name: Docker Hub에 Docker 이미지 Push하기
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/knu-notice-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop knu-notice-server || true
            docker rm knu-notice-server || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/knu-notice-server:latest
            docker run -d --name knu-notice-server -p 8080:8080 \
            -e REDIRECT_URL="${{ secrets.REDIRECT_URL }}" \
            -e DB_URL="${{ secrets.DB_URL }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e COM_URL="${{ secrets.COM_URL }}" \
            -e CLS_URL="${{ secrets.CLS_URL }}" \
            -e CLG_URL="${{ secrets.CLG_URL }}" \
            -e JOB_URL="${{ secrets.JOB_URL }}" \
            -e SCH_URL="${{ secrets.SCH_URL }}" \
            -e EVT_URL="${{ secrets.EVT_URL }}" \
            -e ETC_URL="${{ secrets.ETC_URL }}" \
            -e WEEKLY_URL="${{ secrets.WEEKLY_URL }}" \
            ${{ secrets.DOCKERHUB_USERNAME }}/knu-notice-server:latest
          
      
       
